version: "3.7"

networks:
  i2c:

services:

  localstack:
    image: localstack/localstack:latest
    container_name: s3-local
    ports:
      - "4572:4572"
      - "4566:4566"
      - "8083:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - HOST_TMP_FOLDER=/tmp/localstack
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
    networks:
      - i2c

  loki:
    image: grafana/loki:${LOKI_VERSION}
    container_name: loki-service
    volumes:
      - ./config/loki:/etc/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    networks:
      - i2c

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana-service
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - i2c